name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        haxe: [4.2.5, 4.3.7, 5.0.0-preview.1]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Haxe environment
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: ${{matrix.haxe}}
      - name: Configure Haxe Environment
        run: |
          haxe -version
          haxelib install utest 1.13.2
          haxelib install hxnodejs 12.2.0
          haxelib dev jsoni18n .
      - name: Compile tests
        run: |
          cd tests
          haxe -main Main -lib jsoni18n -lib utest -lib hxnodejs -js build/main.js
      - name: Run tests
        run: |
          cd tests/build
          node main.js
